### ISSUE TITLE
[Bug] 完全卸载 Docker Desktop 会移除 WSL2 的数据

### ISSUE THREAD

**Issue by SettingDust** [Weidows-projects/scoop-3rd#6]
https://docs.docker.com/desktop/uninstall/

**Comment by Weidows** [comment]
@SettingDust  我写的脚本里并没有对 wsl 进行额外操作

卸载参数用的官网给的, 应该不会出问题; 另外对数据的 persist 也不会干涉到 wsl

```json
    "uninstaller": {
        "file": "docker\\Docker Desktop Installer.exe",
        "args": [
            "uninstall",
            "--quiet"
        ]
    },
```

我自己试了一遍卸载+安装, wsl 似乎并没有变化, docker desktop的数据也是在的 (比如登录信息)

所以我好奇卸载后 "移除 wsl 的数据" 是不是指 wsl 中, docker 插入的那两个 distribute 被移除了 (这是正常的)

```shell
>  wsl --list --all                                                  
适用于 Linux 的 Windows 子系统分发:
Ubuntu (默认)
docker-desktop-data
docker-desktop
```

可以用 `wsl --list --all` 看一下wsl默认指向是不是错了

**Comment by SettingDust** [comment]
`docker-desktop-data` 会保有命名的容器卷，所以会被删掉数据，除非全都映射到 Windows 下

**Comment by Weidows** [comment]
scoop uninstall/update 确实会存在删容器的问题

按官方文档说法, 是要手动导出备份

我直接把docker的卸载操作删掉了 (也就是现在没办法通过scoop卸载干净docker, 感觉并无大碍)

现在卸载后再安装, 容器什么的都还在
